config/routes.rb
POACC::Application.routes.draw do

  get "orthpaedics/index"
  
  get "appointments/index"
  get "appointments/new_patient"
  get "appointments/old_patient"
  get "appointments/booked"
  get "appointments/not_booked"

  post "appointments/createold"

  post "appointments/create"

  post "contact/feedback"

  get "patients/old"

  get "practices/index"

  get "staffs/index"

  resources :followups

  resources :assessments

  resources :patients

  resources :appointments

  resources :staffs

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "admin/index"

  resources :contact 

  get "home/index"
  get "home/about"
  get "home/contact"
  get "home/staffservice"
  get "home/woundcare"
  get "home/patients"
  get "home/trauma"
  get "home/bonehealth"
  get "home/bonehealthdetail"
  get "home/charityprojects"
  get "home/fellowships"
  get "home/jobs"
  get "home/ourlinks"
  get "home/densitometryfellowship"
  get "home/bdcourse"
  get "home/trainingcurriculum"
  get "home/cosmotology"
  get "home/correctingtoes"
  get "home/heightincrease"
  get "home/faq"
  root "home#index"

  get 'team' => 'staffs#index'

  

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
	belongs_to :patient
	attr_accessible :day, :requested_time,:approved, :patient_id
	before_save :check_if_approved
	after_save :notify_clinic


	def check_if_approved
		if self.approved
			FeedbackMailer.send_appointment_approval(self).deliver
			puts 'it has been approved'
		end
	end

	def notify_clinic
		if !self.approved
			FeedbackMailer.notify_appointment(self).deliver
		end
	end


end

app/models/assessment.rb
class Assessment < ActiveRecord::Base
	belongs_to :patient
end

app/models/faq.rb
class Faq < ActiveRecord::Base
	belongs_to :faq_category
	attr_accessible :question, :answer, :faq_category_id


	
end

app/models/faq_category.rb
class FaqCategory < ActiveRecord::Base
	has_many :faqs
	attr_accessible :title
end

app/models/followup.rb
class Followup < ActiveRecord::Base
	belongs_to :patient
	attr_accessible :Date, :ClinicalPicture, :Plan
end

app/models/marketing_bullet.rb
class MarketingBullet < ActiveRecord::Base
	attr_accessible :title, :description
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	has_one :assessment
	has_many :followups
	has_many :appointments
	attr_accessible :Name, :Contact, :Email, :Address, :reg_no
end

app/models/patient_numbers.rb
class PatientNumbers < ActiveRecord::Base
	attr_accessible :start, :end
end

app/models/practice.rb
class Practice < ActiveRecord::Base
	attr_accessible :name, :location,:city,:street,:country, :description
	# acts_as_gmappable

	def gmaps4rails_address
		#describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
		"#{self.street}, #{self.city}, #{self.country}"
	end
end

app/models/staff.rb
class Staff < ActiveRecord::Base
	attr_accessible :name, :title, :qualification, :biography, :picture
	has_attached_file :picture, :styles => {
		:tiny => "25x25#",
		:thumbnail => "100x100#",
		:small  => "150x150>",
		:medium => "300x300>" }
		
		attr_accessor :delete_picture

		before_validation {self.picture.clear if self.delete_picture == '1'}
	end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
	attr_accessible :from, :testimonial_text
end

app/models/user_feedback.rb
class UserFeedback < ActiveRecord::Base
end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  before_action :set_assessment, only: [:show, :edit, :update, :destroy]

  # GET /assessments
  # GET /assessments.json
  def index
    @assessments = Assessment.all
  end

  # GET /assessments/1
  # GET /assessments/1.json
  def show
  end

  # GET /assessments/new
  def new
    @assessment = Assessment.new
  end

  # GET /assessments/1/edit
  def edit
  end

  # POST /assessments
  # POST /assessments.json
  def create
    @assessment = Assessment.new(assessment_params)

    respond_to do |format|
      if @assessment.save
        format.html { redirect_to @assessment, notice: 'Assessment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @assessment }
      else
        format.html { render action: 'new' }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assessments/1
  # PATCH/PUT /assessments/1.json
  def update
    respond_to do |format|
      if @assessment.update(assessment_params)
        format.html { redirect_to @assessment, notice: 'Assessment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assessments/1
  # DELETE /assessments/1.json
  def destroy
    @assessment.destroy
    respond_to do |format|
      format.html { redirect_to assessments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assessment
      @assessment = Assessment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assessment_params
      params.require(:assessment).permit(:Complaints, :Clinical, :Investigation)
    end
end

app/helpers/adsense_helper.rb
module AdsenseHelper
  
  # Author: Tomasz Mazur (defkode@gmail.com)
  # http://www.mydigitallife.info/2009/01/17/google-adsense-legacy-old-generation-code-reference-generate-and-get/
  # :slot
  # :theme
  #   :background
  #   :border
  #   :link
  #   :text
  #   :url
  # :channel 10 digits
  # :type "text", "text_image", "image"
  # :alternate_url
  
  # 120×90_0ads_al (4 links)
  # 120×90_0ads_al_s (5 links)
  # 160×90_0ads_al (4 links)
  # 160×90_0ads_al_s (5 links)
  # 180×90_0ads_al (4 links)
  # 180×90_0ads_al_s (5 links)
  # 200×90_0ads_al (4 links)
  # 200×90_0ads_al_s (5 links)
  # 468×15_0ads_al (4 links)
  # 468×15_0ads_al_s (5 links)
  # 728×15_0ads_al (4 links)
  # 728×15_0ads_al_s (5 links)


# links_per_unit
# def link_unit(type, client, theme = {}, options = {})
# end
  
  
  def ad_unit(type, client = "pub-6817444828958491", options = {})
  
    units = {
      :leader_board     => "728x90",
      :wide_skyscraper  => "160x600",
      :banner           => "468x60",
      :half_banner      => "468x30",
      :skyscraper       => "120x600",
      :vertical_banner  => "120x240",
      :large_rectangle  => "336x280",
      :medium_rectangle => "300x250",
      :square           => "250x250",
      :small_square     => "200x200",
      :small_rectangle  => "180x150",
      :button           => "125x125"
    }

    unit = units[type]
    width, height = unit.split("x")
    
    opts = {}
    opts[:google_ad_client] = client
    opts[:google_ad_width]  = width.to_i
    opts[:google_ad_height] = height.to_i
    
    if options[:slot]
      opts[:google_ad_slot] = options[:slot]
    else
      opts[:google_ad_type] = options[:type]
      opts[:google_ad_format] = "#{unit}_as"
      if options[:theme]
        opts[:google_color_border] = options[:theme][:border]
        opts[:google_color_link] = options[:theme][:link]
        opts[:google_color_background] = options[:theme][:background]
        opts[:google_color_text] = options[:theme][:text]
        opts[:google_color_url] = options[:theme][:url]
      end
    end
    
    adsense_opts = opts.map do |k, v|
      v = v.is_a?(String) ? "\"#{v}\"" : v
      "#{k} = #{v};" unless v.blank?
    end.compact.sort.join("\n")
    
    content_tag(:div, [javascript_tag(adsense_opts), content_tag(:script, nil, :type => "text/javascript",
     :src => "http://pagead2.googlesyndication.com/pagead/show_ads.js")].join("\n").html_safe, :class => "google_adsense #{type}")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/followups_helper.rb
module FollowupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/assessments/_form.html.erb
<%= form_for(@assessment) do |f| %>
  <% if @assessment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assessment.errors.count, "error") %> prohibited this assessment from being saved:</h2>

      <ul>
      <% @assessment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Complaints %><br>
    <%= f.text_area :Complaints %>
  </div>
  <div class="field">
    <%= f.label :Clinical %><br>
    <%= f.text_area :Clinical %>
  </div>
  <div class="field">
    <%= f.label :Investigation %><br>
    <%= f.text_area :Investigation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assessments/edit.html.erb
<h1>Editing assessment</h1>

<%= render 'form' %>

<%= link_to 'Show', @assessment %> |
<%= link_to 'Back', assessments_path %>

app/views/assessments/index.html.erb
<h1>Listing assessments</h1>

<table>
  <thead>
    <tr>
      <th>Complaints</th>
      <th>Clinical</th>
      <th>Investigation</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @assessments.each do |assessment| %>
      <tr>
        <td><%= assessment.Complaints %></td>
        <td><%= assessment.Clinical %></td>
        <td><%= assessment.Investigation %></td>
        <td><%= link_to 'Show', assessment %></td>
        <td><%= link_to 'Edit', edit_assessment_path(assessment) %></td>
        <td><%= link_to 'Destroy', assessment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assessment', new_assessment_path %>

app/views/assessments/new.html.erb
<h1>New assessment</h1>

<%= render 'form' %>

<%= link_to 'Back', assessments_path %>

app/views/assessments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Complaints:</strong>
  <%= @assessment.Complaints %>
</p>

<p>
  <strong>Clinical:</strong>
  <%= @assessment.Clinical %>
</p>

<p>
  <strong>Investigation:</strong>
  <%= @assessment.Investigation %>
</p>

<%= link_to 'Edit', edit_assessment_path(@assessment) %> |
<%= link_to 'Back', assessments_path %>